name: flutterissues
description: Flutter Coding Challenge MMS

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  flutter_hooks: ^0.18.2+1
  freezed_annotation: ^1.1.0
  github_sign_in: ^0.0.5-dev.4
  hooks_riverpod: ^1.0.3

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.1

flutter:
  uses-material-design: true
