targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            DateTime:
                name: DateTime
      gql_build|ast_builder:
        enabled: true
        options:
          type_overrides:
            DateTime:
                name: DateTime
      gql_build|data_builder:
        enabled: true
        options:
          schema: graphql|lib/schema/schema.graphql
          type_overrides:
            DateTime:
                name: DateTime
      gql_build|var_builder:
        enabled: true
        options:
          schema: graphql|lib/schema/schema.graphql
          type_overrides:
            DateTime:
                name: DateTime
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: graphql|lib/schema/schema.graphql
          custom_serializers:
            - import: "package:graphql/serializers/date_time_serializer.dart"
              name: DateTimeSerializer

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: graphql|lib/schema/schema.graphql
          type_overrides:
            DateTime:
                name: DateTime