name: graphql
description: GitHub GraphQL Generated Types
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  built_value: ^8.1.4
  gql: ^0.13.0

dev_dependencies:
  ferry_generator: ^0.4.4
  build_runner:
