// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANfdlAT9c-vHkfO2ZE-PcWlAtYzomT9gA',
    appId: '1:246235447691:web:579149491dd753984f6f8e',
    messagingSenderId: '246235447691',
    projectId: 'mms-flutterissues',
    authDomain: 'mms-flutterissues.firebaseapp.com',
    storageBucket: 'mms-flutterissues.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCreYUuzWoeSLI53ygFwiglFAz5ZN8BQoY',
    appId: '1:246235447691:android:253786e5b191bae24f6f8e',
    messagingSenderId: '246235447691',
    projectId: 'mms-flutterissues',
    storageBucket: 'mms-flutterissues.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiaTjnKBJhUoEIvlAf08TQia5pb2D4uGU',
    appId: '1:246235447691:ios:02176aa2edbd76fb4f6f8e',
    messagingSenderId: '246235447691',
    projectId: 'mms-flutterissues',
    storageBucket: 'mms-flutterissues.appspot.com',
    iosClientId: '246235447691-pfifr6r4sgaa2rvelh78fscb2qsf3ooo.apps.googleusercontent.com',
    iosBundleId: 'com.mediamarkt.flutterissues',
  );
}
