name: Test and Build for Android

# Triggered on pushes to the main branch
on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checking out the Repo
      uses: actions/checkout@v1

    - name: Setting up Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    - name: Setting up Flutter
      uses: subosito/flutter-action@v1
    
    - name: Flutter and Dart versions
      run: |
        dart --version
        flutter --version

    - name: Getting the Flutter dependencies
      run: flutter pub get

    # Excluding the generated files
    - name: Checking for any formatting issues
      run: find lib/ packages/ -name "*.dart" ! -name "*.g.dart" ! -name "*.gql.dart" ! -name "*.freezed.dart" | tr '\n' ' ' | xargs flutter format --set-exit-if-changed

    - name: Analyzing the code
      run: flutter analyze .

    # Possible to add the coverage using the --coverage flag
    - name: Running tests
      run: flutter test --no-pub --test-randomize-ordering-seed random

    - name: Building apk
      run: flutter build apk --release

    - name: Uploading the apk to the artifacts
      uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk

    - name: Deploying to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: build/app/outputs/apk/release/app-release.apk
